[package]
name = "fq"
version = "0.1.0"
authors = ["gyng <ng.guoyou@gmail.com>"]
edition = "2018"

[dependencies]
clipboard = "0.5.0"
docopt = "1"
reqwest = "0.9.2"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
